// import { asyncRouterMap, constantRouterMap } from '../../router/index.js';
export default {
  wdlist :  [
      {name:'设备编号',pinyin:'sbbh',value:'',isShow:false},
      {name:'盘管1温度',pinyin:'pg1',value:'',isShow:true},
      {name:'用户1进温度',pinyin:'yhj1',value:'',isShow:true},
      {name:'用户1出温度',pinyin:'yhc1',value:'',isShow:true},
      {name:'水源1进温度',pinyin:'syj1',value:'',isShow:true},
      {name:'水源1出温度',pinyin:'syc1',value:'',isShow:true},
      {name:'压缩机1吸气温度',pinyin:'ysjxq1',value:'',isShow:true},
      {name:'压缩机1排气温度',pinyin:'ysjpq1',value:'',isShow:true},
      {name:'盘管2温度',pinyin:'pg2',value:'',isShow:true},
      {name:'用户2进温度',pinyin:'yhj2',value:'',isShow:true},
      {name:'用户2出温度',pinyin:'yhc2',value:'',isShow:true},
      {name:'水源2进温度',pinyin:'syj2',value:'',isShow:true},
      {name:'水源2出温度',pinyin:'syc2',value:'',isShow:true},
      {name:'压缩机2吸气温度',pinyin:'ysjxq2',value:'',isShow:true},
      {name:'压缩机2排气温度',pinyin:'ysjpq2',value:'',isShow:true},
      {name:'环境温度',pinyin:'hj',value:'',isShow:true},
      {name:'预留温度1',pinyin:'ylwd1',value:'',isShow:true},
      {name:'预留温度2',pinyin:'ylwd2',value:'',isShow:true},
      {name:'预留温度3',pinyin:'ylwd3',value:'',isShow:true},
      {name:'预留温度4',pinyin:'ylwd4',value:'',isShow:true},
      {name:'膨胀阀1开度',pinyin:'pzfkd1',value:'',isShow:false},
      {name:'膨胀阀2开度',pinyin:'pzfkd2',value:'',isShow:false},
  ],
  role:null,
  // routers: constantRouterMap,
  // addRouters: []
}
